### PR TITLE
Added manageOpenLabel which seperates the compilation and showing of pop...

### PR DESCRIPTION
**Pull request by jessertaylor**
...ups and labels. Added getLabelScope for independent label scope.

### CODE REVIEW

**Comment by tombatossals** [comment]
Fantastic changes @jessertaylor, thanks for sharing.

**Comment by jessertaylor** [comment]
@tombatossals Thanks :+1:

**Comment by jessertaylor** [comment]
@tombatossals any ideas why it failed? was it the order of the commits?

**Comment by tombatossals** [comment]
Hi @jessertaylor, it's easy don't worry, I ran the tests and some of them were not working, it's because not all the markers need to load the label functionality. It only needed to check that the Leaflet.Label plugin was loaded before trying to add its logic, and that the getLabel & unbindLabel functions were defined before executing them.

You can try to run the unitary tests by yourself after coding some changes,  with this command:

```
grunt test-unit
```

Cheers

**Comment by jessertaylor** [comment]
ha, ok that's weird because the check was like that before my PR :) anyway thanks again looking forward to a release :)

**Pull request merged**
