### PR TITLE
Markers with angular-powered custom icons

### PR DESCRIPTION
**Pull request by ValentinH**
The idea is to be able to create a custom (angular-enabled) icon for a marker that can be anything you want (directives?). The content of the icon is managed by angular and can be autonomous.

Discussion started here: #843
Simple demo with the basic idea: http://jsfiddle.net/c7bhqf8c/1/ 
Demo with D3.js pie charts : http://codepen.io/ValentinH/pen/RPOjQO/
> The demo 1 is using Leaflet 1.0.beta because in the stable version the click event on the input is trapped and so the input can't be edited... But the concept works with the stable version (see charts demo).

It requires this plugin to be able to add a dom element inside the icon: https://github.com/ValentinH/Leaflet.DomMarkers

Example of usage:
```js
  angular.extend($scope, {
    center: {
        lat: 46,
        lng: 4,
        zoom: 5
    },
    markers: {
        paris: {
            lat: 48.8588589,
            lng: 2.3470599,
            icon: {
                type: 'dom',
                iconSize: [60, 60],
                className: 'dom-marker1',
                getMarkerScope: function () {
                    return $scope
                },
                template: '<div>{{ dynamic_content }}</div>'
            }
        }
    }
});
```

Any feedback on the implementation is welcome! ;)

### CODE REVIEW

**Comment by tombatossals** [comment]
LGTM. What do you think @nmccready?

**Comment by ValentinH** [comment]
Do you think there is somehow a way to embed the DomMarkers plugin directly inside the directive?

**Comment by tombatossals** [comment]
What we're doing with others leaflet plugins is to include the required javascript in the HTML, and if the user forget to include it, a warning is shown in the console noticing it. This way the main library doesn't grow excesively and the user only include what he/she needs.

Say that, it would be very simple for a final user to concat/uglify all the js files in a single file, obtaining the same result. I think this is a good solution.

Take a look at the source code of this example, the Leaflet.Marker.Rotate.js plugin is included in the JS:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/rotation-example

What do you think?

**Comment by ValentinH** [comment]
OK to keep the plugin outside, I actually already wrote the code the fire a warning when it is not loaded.

I just noticed something weird in the file changed tab: there are some lines that I haven't modified but are modified. Maybe I did not start from the very last version... Like [this](https://github.com/tombatossals/angular-leaflet-directive/pull/890/files#diff-b2caf2ded6908dbf52be148242134e29R1375), [this](https://github.com/tombatossals/angular-leaflet-directive/pull/890/files#diff-b2caf2ded6908dbf52be148242134e29R1463) or [this](https://github.com/tombatossals/angular-leaflet-directive/pull/890/files#diff-b2caf2ded6908dbf52be148242134e29R4506). What do you think?

**Comment by tombatossals** [comment]
Yess, there has been some merges since your code, but it seems to merge with no conflicts.

You could rebase&push your code to make it cleaner if you want, but I think it will merge without problems.

**Comment by ValentinH** [comment]
Actually only the dist files have extra edits and this surely because a previous merge didn't generate the latest dist files. So it is OK I think.

**Comment by nmccready** [comment]
LGM

**Comment by ValentinH** [comment]
Should we add the charts demo to the examples?

**Comment by woods9910** [comment]
Any formal example for this? Cant seem to get it working.

**Comment by ValentinH** [comment]
This doesn't work: http://codepen.io/ValentinH/pen/RPOjQO/?

**Comment by woods9910** [comment]
lat: parseFloat(marker.latitude),
                lng: parseFloat(marker.longitude),
                icon: {
                    type: 'dom',
                    iconSize: [60, 60],
                    className: 'dom-marker1',
                    getMarkerScope: function () {
                        return $scope
                    },
                    template: '<div>{{ marker.id }}</div>'
                }

This is my marker, and I've included leaflet.dom-markers.js. Is there something I'm missing? Not getting anything just shows default markers.

**Comment by ValentinH** [comment]
Could you please provide a JSFiddle/Codepen showing your issue?

**Comment by woods9910** [comment]
Okay, well I edited your codepen and just simplified it to get rid of all the d3 stuff and it worked, but when I paste the exact same thing into my project it doesnt work. Could it have something to do with the order I'm including the js files? Not sure what else the cause could be. I do know that it never reaches the createIcon function in the plugin.

**Comment by ValentinH** [comment]
Yes the order is important. You need to include in this order:
1. AngularJS
2. Leaflet
3. Leaflet.DomMarkers
4. Angular Leaflet Directive
5. Your own JS files

Do you have any error showing in the console?

**Comment by ValentinH** [comment]
Indeed the hosted files will be updated in the next release.

**Pull request merged**
