### PR TITLE
feat(layers): Added the possibility to manually refresh a layer

### PR DESCRIPTION
**Pull request by tombatossals**
Refresh the layer using the doRefresh property.

Commented by @pieterjandesmedt here:
https://github.com/tombatossals/angular-leaflet-directive/issues/730#issuecomment-95597177

### CODE REVIEW

**Comment by nmccready** [comment]
LGTM

**Comment by pieterjandesmedt** [comment]
Hey guys, why do you set .doRefresh to false? 
```javascript
if (newBaseLayers[name].doRefresh) {
    newBaseLayers[name].doRefresh = false;
}
```
I thinks this disables continuous updates after the first update right?
Also, it breaks unit test `layers.watch.markers should add and remove layers in watch` in `layersDirective.watch.markersSpec.js`

**Comment by tombatossals** [comment]
Yess @pieterjandesmedt, that's because I understood that the "doRefresh" property is a one-time-use action, so from the controller you set this property and the directive processes it in the life-cycle, after processed it returns to the false value.

I opted for this approach because if you don't have an imperative switch to refresh,  when does the layer has to be refreshed? Every X seconds? If not set an interval, every digest cycle the layer would be deleted and re-created.

You're right about the tests, it needed an extra check, last commit solved it.

Maybe we could improve this. What do you think about broadcasting a message from controller to directive announcing the need to refresh the layer?

**Comment by pieterjandesmedt** [comment]
Aha, I see what you mean. I don't think broadcasting a message is necessary. The layers watch should pick it up when a controller or service sets `doRefresh` to `true`, right?

**Comment by tombatossals** [comment]
Yess, this would be the example, based on the one you provide:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/layers/refresh-overlay-every-minute-example

The idea is that you set the layer property "doRefresh" to true, and immediatly this is processed in the directive watch, which re-creates the layer and sets the doRefresh property to false.

**Comment by pieterjandesmedt** [comment]
Ok, fine by me!

**Pull request merged**
