### PR TITLE
Fix updating markers and managing popups

### PR DESCRIPTION
**Pull request by cgat**
Lots of logic for marker updating was contained in the addMarkerWatch callback. If you didn't watch individual markers, then markers weren't getting updated properly. This used to work because the directive simply replaced markers on update, but with recent refactors, this is no longer the case. The addMarkerWatch callback has been renamed _updateMarker and made available to the marker directive. It is used to update markers in _addMarkers.

See #812 for more info about how this deals with the popup problem

### CODE REVIEW

**Comment by jessertaylor** [comment]
Will have a look through but I'll say this before @nmccready does :)  - you need to use these commit message guidelines https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines in your commit messages http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git

**Comment by cgat** [comment]
Okay, I'm off for the weekend. Might not get to this until early next week.

**Comment by cgat** [comment]
@jessertaylor Thanks for merging the pull request. Now that these commits are public, I don't think I can edit the commit messages without rewriting history (commit --amend rewrites the commit id). Please correct me if I'm wrong. Sorry about this, I should have observed the contribution guidelines from the get go.

**Comment by nmccready** [comment]
No worries, rather get the fix in. I can add a commit message in on doing the pre-release. If you have a commit msg in mind; just leave it here. I'll copy it in.

**Comment by cgat** [comment]
@nmccready 

feat(leafletMarkersHelper, markers): Fix updating markers and managing popups

   Lots of logic for marker updating was contained in the addMarkerWatch callback. If you didn't watch individual markers, then markers weren't getting updated properly. This used to work because the directive simply replaced markers on update, but with recent refactors, this is no longer the case. The addMarkerWatch watch callback is now _updateMarker and made available to the marker directive. It is used to update markers in _addMarkers. Before this commit, _addMarkers just ignored markers that already exists, now it updates.
   We now use marker.popupOpen() to handle popup logic (when focus is set to true, ensure popup gets opened). When the popup event is fired, manageOpenPopup will be used to compile the popup if necessary.

Fixes #812

**Pull request merged**
