### PR TITLE
Examples rework and viewer

### PR DESCRIPTION
**Pull request by tombatossals**
Hi guys, I finally finished this work. It has been intense.

This is a rework of all the examples added in the "examples" directory, with two main changes.

1. There is a "viewer" of examples, were we can explore and navigate between all the examples, categorized.
2. All the examples can be viewed as a standalone version.

This is accomplished by following a standard creating the HTML examples, and by a NodeJS script.

When adding a new example , or modifying an existing one, you can add it to the viewer executing:

```
grunt examples
```

There are a few examples wich doesn't work now, and that's because there has been a lot of changes lastly on the library, I will fix them (or fix the library bug if present) in the meantime.

The protractor tests needs to be modified too, but that will be another PR.

You can see the work explained here in this "example-browser":

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html

### CODE REVIEW

**Comment by nmccready** [comment]
Is it possible to rebase? This is massive. I trust you and it is mainly examples anyways. But the github reviewer is throwing up and slow; so this is hard to digest.

**Comment by tombatossals** [comment]
Mmm... I'm recreating this PR again, it has messed up a little with all the commits these days

**Comment by nmccready** [comment]
If rebase is too difficult just merge the latest changes in. I need to work on a possible bug for leafletData

**Comment by nmccready** [comment]
k

**Comment by nmccready** [comment]
btw we should proabably add `grunt d ` to travis. I just pulled latest and it does not build.

**Comment by nmccready** [comment]
I'll push up build fix immediately.

**Comment by nmccready** [comment]
done

**Pull request closed without merging**
