### PR TITLE
Fix illegal id from the changelog

### PR DESCRIPTION
**Pull request by simison**
In HTML `id=""` cannot start with a number.

### CODE REVIEW

**Comment by nmccready** [comment]
Speaking of changelog feel like updating us to the latest conventional changelog? There constantly seem to be quirks with the build process of angular commit being missed where I have to manually enter them in.

**Comment by simison** [comment]
Hmm, I don't follow, could you elaborate a bit more?

**Comment by nmccready** [comment]
Here:

We are using https://github.com/btford/grunt-conventional-changelog which should automate our change logs. Recently they updated to 5.X and were on [1.X](https://github.com/tombatossals/angular-leaflet-directive/blob/master/package.json#L56). There are a ton of breaking changes.

**Comment by nmccready** [comment]
Used here: https://github.com/tombatossals/angular-leaflet-directive/blob/master/grunt/changelog.js the 0.9.8 bug was in there as well.

**Pull request merged**
