### PR TITLE
Fix issue with autopan for ng-include

### PR DESCRIPTION
**Pull request by MarkAPhillips**
Please review - I have tested this locally and works as expected - thanks

### CODE REVIEW

**Comment by jessertaylor** [comment]
Travis is failing - I don't think it is the code

**Comment by jessertaylor** [comment]
I think you should get rid of adjustPan and just set it like

```
                if (popup.options.autoPan) {
                    popup._adjustPan();
                }
```

Why the need to specify adjustPan true? And also, for popups without ng-include it will not pass adjustPan true, thus anything with autoPan true, without ng-include won't work. Hope this makes sense.

tldr; remove adjustPan

**Comment by MarkAPhillips** [comment]
Yep no problem I was not sure if it was required when ng-include was not specified - but makes sense 
Travis is timing out for some reason on the karma unit tests.

**Comment by jessertaylor** [comment]
@nmccready

**Comment by jessertaylor** [comment]
@MarkAPhillips try to do a re-commit with the changes if possible.

**Comment by nmccready** [comment]
LGTM, ill try and force Travis to re-run

**Comment by MarkAPhillips** [comment]
OK will do

**Comment by nmccready** [comment]
Looks like karma is hanging on travis

**Comment by nmccready** [comment]
I will need to pull this down locally and test it . Travis is still not passing and it could be karma itself.

**Comment by nmccready** [comment]
Karma is hanging locally I need to fix this first.

**Comment by nmccready** [comment]
Please pull down latest and merge.

**Pull request merged**
