### PR TITLE
Routing machine feature 503

### PR DESCRIPTION
**Pull request by jasmo2**
Aparently is already ok, but you havent merge it yet.
I would me awesome
Here are the differences between the two branches.
https://github.com/tombatossals/angular-leaflet-directive/compare/master...routing-machine-feature-503

### CODE REVIEW

**Comment by jasmo2** [comment]
https://github.com/tombatossals/angular-leaflet-directive/compare/master...routing-machine-feature-503

**Comment by nmccready** [comment]
Conflicts need to be resolved.

**Comment by jasmo2** [comment]
I will like to help. Tell me which conflicts.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Mon, Oct 5, 2015 at 6:43 AM -0700, "nmccready" <notifications@github.com<mailto:notifications@github.com>> wrote:


Conflicts need to be resolved.

-

**Comment by nmccready** [comment]
I think we should merge this ourselves as I am sure @tombatossals has good reasons for not including this yet. Anyway; he or I or another active dev should resolve the conflicts locally. Therefore please make this a ticket. Reference this if you'd like.

**Pull request closed without merging**
