### PR TITLE
Leaflet.heat layer

### PR DESCRIPTION
**Pull request by tombatossals**
Added a new type of layer, "heat", which implements the Leaflet.heat plugins (https://github.com/Leaflet/Leaflet.heat).

* Added the new layer.
* Added an example of use.
* Renamed the old "heatmap" layer to "webGLHeatmap"

### CODE REVIEW

**Comment by nmccready** [comment]
This is not passing

**Comment by jessertaylor** [comment]
@nmccready Don't think it's a code issue?

bower ECMDERR       Failed to execute "git ls-remote --tags --heads git@github.com:Leaflet/Leaflet.heat.git", exit code of #128 Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts. Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

**Comment by nmccready** [comment]
Rebuilding

**Comment by nmccready** [comment]
I think this is an issue, but I'll merge it anyway and fix it right away.

**Pull request merged**
