### PR TITLE
add support for passing a center offset

### PR DESCRIPTION
**Pull request by leosvelperez**
the center now could be and object like:
{lat: 32, lng: -96, zoom: 4, offset: [400, 0]}

the offset property can be a number or an array of two values where if it's a number it's the offset from the left and if it's an array the first position is the offset from the left and the second one is from the top, if negative values are provided the orientation is reversed, the values for the offset are in pixels and if not offset property is passed then it's ignored

### CODE REVIEW

**Comment by simison** [comment]
What sort of situation you have where you'd need this?

**Comment by leosvelperez** [comment]
I have an app where there is a collapsible sidebar on the left side. The map is full width with a part of it under the sidebar and that's why I need the center of the map to have the width of the sidebar as an offset. Before I did this, I tried make a map.setView but because the map is already created with a center then mi call to cause a movement in the map to translate it to the place I want and I don't want that kind of movement. The Leaflet map can be created with the offset already calculated but the directive don't provide a way to do it, at least none that I'm aware of. It's a small change that doesn't break what exists today but allows support for this kind of situation that I think it's a very common one. Let me know if there is another way of doing this.
Regards.

**Comment by nmccready** [comment]
Can this not be solved via CSS?

**Comment by leosvelperez** [comment]
I asume you are thinking about having the map not full width and enlarge it or shrink it when the sidebar is collpased or not. First of all, that's less performant and second, I used CSS and when I enlarged the map to cover the space left by the collapsed sidebar then on the opposite side there is a space I think the same size enlarged that doesn't render the tiles. It's like even when the map is full width, the inner component still have the previous width.
I don't see the problem of including the piece of code submitted. It doesn't affect the rest of the functionality, it's a clean way of solving a common problem, it allows to do something that Leaflet provides an easy and native way to do it and this directive doesn't allow me to in a natural way. If the config proposed it's no passed, it simply behaves the same way as before, it doesn't affect any of the previous behaviour. I'm using it in a project and it works like a charm.

**Comment by nmccready** [comment]
@leosvelperez the fact that it works and does not effect existing code is irrelevant if it is code we do not need and it can be done via CSS then why merge it. However, you have my ear when you talk performance. 

It would probably do wonders for everyone if you PR'd this with an example on plnkr and in the code base. You could even compare your solution vs say doing it in CSS. This would do way more than just describing the situation. It's not that I do not believe you but it gives me and others a better understanding of your use case.

**Comment by nmccready** [comment]
Also specs would be appreciated on your new addition as well.

**Comment by simison** [comment]
>Leaflet provides an easy and native way to do it and this directive doesn't allow me to in a natural way

At first I was thinking this PR should be done against Leaflet, not Angular-Leaflet. Can you elaborate a bit more how you'd go around the issue with native Leaflet?

**Comment by nmccready** [comment]
ping? Were looking for some feedback please.

**Comment by nmccready** [comment]
Closing until we get some feedback. I will re-open if need be.

**Pull request closed without merging**
