### PR TITLE
Fixed popup positioning after $compile. Refactored the open popup functionality

### PR DESCRIPTION
**Pull request by jessertaylor**

### CODE REVIEW

**Comment by jessertaylor** [comment]
@nmccready

**Comment by nmccready** [comment]
@jessertaylor the bump should come after the merge as you have the tag. I mean I can merge this and then you push the tag. However, its not generally a good idea especially if you change anything. I recommend reverting the bump.

**Comment by jessertaylor** [comment]
@nmccready no worries, that ok?

**Comment by nmccready** [comment]
LGTM

**Comment by nmccready** [comment]
btw if you could in future commits start using angularjs commit conventions `fix(whatever): summary`

**Comment by jessertaylor** [comment]
@nmccready Will do. Do you want me to push a build or you ok to do one?

**Comment by nmccready** [comment]
I want to make sure changelog is working how I want it. So once that is flushed out you can do it. I had to make some changes to it on angular-google-maps.

**Comment by nmccready** [comment]
@jessertaylor done

**Pull request merged**
