### PR TITLE
Add bounds options support

### PR DESCRIPTION
**Pull request by ValentinH**
Add the code to support bounds options as described in #770.

```js
{
   markers: {}
   bounds: {
      northEast: {},
      southWest: {},
      options: {
          padding: [50, 50]
      }
   }
}
```

### CODE REVIEW

**Comment by nmccready** [comment]
care to add a spec?

**Comment by ValentinH** [comment]
Sorry, what do you mean by a spec? Do you have an example please?

**Comment by nmccready** [comment]
Add an `it` test to here https://github.com/tombatossals/angular-leaflet-directive/blob/master/test/unit/leafletDirectiveSpec.js#L7-L54 to verify your new options work. It will help prevent regressions later.

**Comment by ValentinH** [comment]
Oh OK got it.

**Comment by nmccready** [comment]
:+1:

**Comment by ValentinH** [comment]
Wouldn't it be better to add a spec in boundsDirectiveSpec?

**Comment by ValentinH** [comment]
I am not very proud of my spec but there is no way to tests the actual options passed to Leaflet.
I just verify that the bounds we provided to the directive are different from the map's bounds.
Other tests already ensure, that the bounds are correct without the options...

**Comment by nmccready** [comment]
LGTM

**Pull request merged**
